# -*- coding: utf-8 -*-
"""mnist_classifier

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RNMv_tRDSeDGiFIggdp2HIGZyV9-bB3w
"""

import numpy as np
import joblib

# Load trained model
model = joblib.load("mnist_model.pkl")

def predict_digit(image):
    # Resize and preprocess image
    x = image.flatten().reshape(1, -1) / 255.0
    pred = model.predict(x)[0]
    probs = model.predict_proba(x)[0]
    return pred, probs
